/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.hmkang.TiUA;
import android.app.Application;
import android.content.Context;
import android.content.Intent;
import android.app.Activity;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.hmkang.TiUA.IntentReceiver;
import com.urbanairship.AirshipConfigOptions;
import com.urbanairship.Logger;
import com.urbanairship.UAirship;
import com.urbanairship.push.CustomPushNotificationBuilder;
import com.urbanairship.push.PushManager;
import com.urbanairship.push.PushPreferences;


@Kroll.module(name="Tiua", id="com.hmkang.TiUA")
public class TiuaModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TiuaModule";
	private static final boolean DBG = TiConfig.LOGD;
    private static TiuaModule _THIS;
    private AirshipConfigOptions airshipConfig;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public TiuaModule(TiContext tiContext)
	{
		super(tiContext);
        _THIS = this;
        airshipConfig = null;
	}

    static TiuaModule getInstance() {
        return _THIS;
    }
/*
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
        AirshipConfigOptions options = AirshipConfigOptions.loadDefaultOptions(app);
        UAirship.takeOff(app, options);

        PushManager.enablePush();

		PushPreferences prefs = PushManager.shared().getPreferences();
		Logger.info("My Application onCreate - App APID: " + prefs.getPushId());

        // Set intent receiver
        PushManager.shared().setIntentReceiver(IntentReceiver.class);
	}
*/
    @Kroll.method
    public void setAirshipConfig(KrollDict param){
        AirshipConfigOptions options = new AirshipConfigOptions();

        options.inProduction = (Boolean)param.get("inProduction");
        //options.hostURL = (String)param.get("hostURL");
        options.pushServiceEnabled = (Boolean)param.get("pushServiceEnabled");
        options.c2dmSender = (String)param.get("c2dmSender");
        options.transport = (String)param.get("transport");
        options.productionAppKey = (String)param.get("productionAppKey");
        options.productionAppSecret = (String)param.get("productionAppSecret");
        options.developmentAppKey = (String)param.get("developmentAppKey");
        options.developmentAppSecret = (String)param.get("developmentAppSecret");

        airshipConfig = options;
    }
    private AirshipConfigOptions getAirshipConfig() {
        return airshipConfig;
    }
    private void registerUA() {
		Log.d(LCAT, "inside registerUA()");

        UAirship.takeOff(getTiContext().getTiApp(), getAirshipConfig());

        PushManager.enablePush();

		PushPreferences prefs = PushManager.shared().getPreferences();
		Logger.info("My Application onCreate - App APID: " + prefs.getPushId());

        // Set intent receiver
        PushManager.shared().setIntentReceiver(IntentReceiver.class);
    }
	@Kroll.method
    public void registerPush(KrollDict param) {
		Log.d(LCAT, "inside registerPush()");

        Activity myAct = getTiContext().getTiApp().getCurrentActivity();
        Log.d(LCAT, "className: " +myAct.getComponentName());
        setAirshipConfig(param);
        registerUA();
    }
}

